In [14]:
#Imports sql python connector, run this code first to set server credentials
import mysql.connector as connector

user = "root"
password = "SQLpassword!23"
db = "little_lemon"

In [15]:
#Show available tables in database. This is important because of syntax sensitive in SQL.
try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor(buffered=True)

    #Execute query
    show_table = "SHOW TABLES FROM little_lemon;"
    cursor.execute(show_table)

    #Fetch and print column names
    print(cursor.column_names)

    #Fetch and print results
    results = cursor.fetchall()
    for i in results:
        print(i[0])
    
    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

('Tables_in_little_lemon',)
Address
Bookings
Customers
Delivery
Menu
MenuItems
Orders
Staff

In [16]:
#Showing first 20 rows of data from selected table. Please feel free to swap tables in SQL statement.
try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor(buffered=True)

    #Execute query
    check_table = "SELECT * FROM Customers;"
    cursor.execute(check_table)

    #Fetch and print column names
    cols = cursor.column_names
    print(cols)
    
    #Fetch and print results
    results = cursor.fetchmany(20)
    for row in results:
        #Prints the results in the row on the same line
        for col in row:
            print(col, end=' , ')
        print()
    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

('CustomerID', 'FirstName', 'LastName', 'AddressID')
1 , Laney , Fadden , 1 ,
2 , Giacopo , Bramich , 2 ,
3 , Lia , Bonar , 3 ,
4 , Merrill , Baudon , 4 ,
5 , Tasia , Fautly , 5 ,
6 , Angel , Veschambre , 6 ,
7 , Sheilah , Maestro , 7 ,
8 , Audie , Willcocks , 8 ,
9 , Mart , Malsher , 9 ,
10 , Magdalen , Lacheze , 10 ,
11 , Margarita , Mancktelow , 11 ,
12 , Ashil , Brogini , 12 ,
13 , Arthur , Mathewson , 13 ,
14 , Ennis , Dungate , 14 ,
15 , Tiffani , Halstead , 15 ,
16 , Roddie , Winterbotham , 16 ,
17 , Pincas , Stearn , 17 ,
18 , Tony , Crabtree , 18 ,
19 , Tamarah , Filasov , 19 ,
20 , Pen , Pruce , 20 ,

In [17]:
try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor(buffered=True)

    #Execute query
    customer_promo60 = """
            SELECT o.OrdersID, o.Sales - o.Discount AS TotalCost, CONCAT(c.FirstName, ' ', c.LastName) AS CustomerName
            FROM Orders AS o 
            LEFT JOIN Customers AS c ON o.CustomerID = c.CustomerID
            HAVING TotalCost > %s
    """
    cursor.execute(customer_promo60, (60,))

    #Print results
    results = cursor.fetchmany(10)
    print("Orders over $60\n")
    for i in results:
        print(f"Order ID: {i[0]} \n{i[2]} - ${i[1]}\n")

    #User input to load more - potential erratic behavior based on connector and cursor object
    confirmation = input("Would you like to load the next 50 results?(y/n) ")

    #Fetch 50 more results if users indicates y
    if confirmation.lower() == 'y':
        results_50 = cursor.fetchmany(50)
        print("Here are the next 50 results\n")
        for t in results_50:
            print(f"Order ID: {t[0]} \n{t[2]} - ${t[1]}\n")

    else:
        pass
    
    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

Orders over $60

Order ID: 1
Laney Fadden - $167.50

Order ID: 2
Giacopo Bramich - $337.50

Order ID: 3
Lia Bonar - $101.98

Order ID: 4
Merrill Baudon - $318.77

Order ID: 5
Tasia Fautly - $428.95

Order ID: 6
Angel Veschambre - $225.16

Order ID: 7
Sheilah Maestro - $447.60

Order ID: 8
Audie Willcocks - $246.09

Order ID: 9
Mart Malsher - $275.29

Order ID: 10
Magdalen Lacheze - $66.66

Would you like to load the next 50 results?(y/n)  y

Here are the next 50 results

Order ID: 11
Margarita Mancktelow - $198.33

Order ID: 15
Tiffani Halstead - $100.72

Order ID: 16
Roddie Winterbotham - $175.76

Order ID: 17
Pincas Stearn - $68.12

Order ID: 18
Tony Crabtree - $72.46

Order ID: 19
Tamarah Filasov - $81.07

Order ID: 20
Pen Pruce - $106.61

Order ID: 21
Boot Burree - $167.17

Order ID: 22
Sabra Calbreath - $343.38

Order ID: 24
Anders Stowe - $294.56

Order ID: 25
Locke Janaway - $448.80

Order ID: 26
Kaylyn Colebourne - $253.51

Order ID: 27
Noni Quickenden - $373.86

Order ID: 28
Alan Paskell - $240.02

Order ID: 29
Anny Pattemore - $216.11

Order ID: 30
Les Harmson - $99.16

Order ID: 31
Horatio Lundy - $157.65

Order ID: 32
Sibley Rodder - $132.40

Order ID: 33
Dniren Copperwaite - $124.70

Order ID: 35
Alison Jamieson - $126.53

Order ID: 36
Dre Danher - $148.71

Order ID: 38
Adiana Shirtliff - $108.59

Order ID: 40
Lenci McFadzean - $169.99

Order ID: 41
Uriel Grooby - $107.16

Order ID: 42
Jillayne Gaiford - $298.42

Order ID: 44
Ilario Michie - $230.76

Order ID: 45
Sarah Plaschke - $450.00

Order ID: 46
Skipp Lowater - $277.96

Order ID: 47
Maddalena Wolfinger - $441.00

Order ID: 48
Mariquilla Labbe - $327.50

Order ID: 49
Cornelius Harkess - $231.47

Order ID: 50
Erv Padrick - $124.00

Order ID: 51
Fielding Struys - $179.32

Order ID: 52
Purcell Eyer - $166.60

Order ID: 53
Pietra Dibdall - $207.02

Order ID: 54
Dyanne Labbet - $84.63

Order ID: 55
Elsworth Stannas - $104.26

Order ID: 57
Calvin Aucock - $76.27

Order ID: 58
Prudence Eastlake - $108.62

Order ID: 62
Jackie Kment - $84.94

Order ID: 63
Phil Schapero - $167.50

Order ID: 64
Giusto Sheavills - $337.50

Order ID: 65
Emmalynne Hairs - $101.98

Order ID: 66
Mirna Rosita - $318.77

Order ID: 67
Alard Briat - $428.95

Order ID: 68
Ferdinand Fowley - $225.16

Order ID: 69
Averell Joint - $447.60

Order ID: 70
Deane Benbough - $246.09

Order ID: 71
Grenville Hyne - $275.29

Order ID: 72
Asia McNess - $66.66

In [19]:
#Adding in Booking Data

try:
    #Establish connection to server
    connection = connector.connect(
        user = user,
        password = password,
        db = db)
    
    #Create cursor object
    cursor = connection.cursor()

    #Query statement and execute
    insert_bookings = """
    INSERT INTO Bookings (BookingID, TableNumber, BookingDate, CustomerID) 
    VALUES
        (15, 5, '2022-12-14', 18),
        (16, 11, '2022-12-14', 4),
        (17, 6, '2022-12-15', 2),
        (18, 4, '2022-12-15', 17);
    """

    cursor.execute(insert_bookings)

    #Committing data to database
    connection.commit()
    
    print("Bookings data successfully entered")

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

Bookings data successfully entered

In [20]:
#Finds all created procedures
try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()

    #Query statement and Execute
    check_procedures = """
            SELECT ROUTINE_NAME 
            FROM information_schema.ROUTINES 
            WHERE ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_SCHEMA = 'little_lemon';

    """
    cursor.execute(check_procedures)

    print(cursor.column_names)

    results = cursor.fetchall()
    for i in results:
        print(i)

    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

('ROUTINE_NAME',)
('AddBooking',)
('CancelBooking',)
('CheckBooking',)
('GetMaxQuantity',)
('UpdateBooking',)

In [21]:
#Create get max quantity procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()

    drop_procedure = """
        DROP PROCEDURE IF EXISTS `GetMaxQuantity`;
    """
    cursor.execute(drop_procedure)
    
    #Execute query
    create_maxquantity = """            
            CREATE PROCEDURE `GetMaxQuantity`()
            BEGIN
            	SELECT MAX(Quantity) AS "Max Quantity in Order" FROM Orders;
            END
    """
    cursor.execute(create_maxquantity)

    print("MySQL procedure successfully created")

    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

MySQL procedure successfully created

In [22]:
#Calling max quantity procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()

    #SQL query and Execute query
    max_quant = """
        CALL GetMaxQuantity();
    """
    cursor.execute(max_quant)
    print(cursor.column_names)
    
    results = cursor.fetchall()
    for i in results:
        print(i)
    
    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

('Max Quantity in Order',)
(3,)

In [26]:
#Create check booking procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()

    drop_procedure = """
        DROP PROCEDURE IF EXISTS `CheckBooking`;
    """
    cursor.execute(drop_procedure)
    
    #Execute query
    create_checkbooking = """            
            CREATE PROCEDURE `CheckBooking`(IN booking_date DATE, IN table_no INT)
            BEGIN
                DECLARE checkRes BOOLEAN;
                
                SELECT COUNT(*) INTO checkRes FROM Bookings
                WHERE BookingDate = booking_date AND TableNumber = table_no;

                IF checkRes THEN
                    SELECT CONCAT('The date ', booking_date, ' and table ', table_no, ' are already booked.') AS Message;
                ELSE 
                    SELECT CONCAT('Table ', table_no, ' is available on ', booking_date, '.') AS Message;
                END IF;    
            END
    """
    cursor.execute(create_checkbooking)

    print("MySQL procedure successfully created")

    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

MySQL procedure successfully created

In [39]:
#Using check booking procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()
    
    #Execute query
    checkbooking = """            
            CALL CheckBooking('2022-12-12', 6)
    """
    print("Checking booking...")
    
    print("Your results are below:")
    cursor.execute(checkbooking)
   
    results = cursor.fetchall()
    print(results)

    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

Checking booking...
Your results are below:
[('The date 2022-12-12 and table 6 are already booked.',)]

In [24]:
#Create update booking procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()

    drop_procedure = """
        DROP PROCEDURE IF EXISTS `UpdateBooking`;
    """
    cursor.execute(drop_procedure)
    
    #Execute query
    create_updatebooking = """            
            CREATE PROCEDURE `UpdateBooking`(IN booking_id INT, IN date DATE)
            BEGIN
                UPDATE Bookings
                SET BookingDate = date
                WHERE BookingID = booking_id;
            END
    """
    cursor.execute(create_updatebooking)

    print("MySQL procedure successfully created")

    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

MySQL procedure successfully created

In [41]:
#Using update booking procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()

    #Asking for user-input
    booking_id = input("Please enter your Booking ID: ")
    new_booking_date = input("Please enter the new Booking Date (YYYY-MM-DD): ")

    # Convert Booking ID to integer if necessary
    booking_id = int(booking_id)
    
    #SQL query to check previous booking date & execute
    booking = """
    SELECT BookingID, BookingDate, TableNumber FROM Bookings WHERE BookingID = %s;
    """
    cursor.execute(booking, (booking_id,))
    booking_results1 = cursor.fetchall()
    for i in booking_results1:
        print(f"\nYou are requesting a change for Booking ID #{i[0]}.\nYour previous booking date was: {i[1]}")

    #Calling procedure to update
    update_booking = """            
            CALL UpdateBooking(%s, %s)
    """
    print("\nInitating booking update...\n")
    
    cursor.execute(update_booking, (booking_id, new_booking_date))
    
    confirm = input("Do you want to complete the booking? (y/n) ")
    if confirm == 'y':
        connection.commit()
        
        cursor.execute(booking, (booking_id,))
        booking_results2 = cursor.fetchall()
        for i in booking_results2:
            print(f"Your new booking date is {i[1]}")
            
    else:
        print("Your booking update has been cancelled.")    

    cursor.close()
    
except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

Please enter your Booking ID:  2
Please enter the new Booking Date (YYYY-MM-DD):  2022-12-15

You are requesting a change for Booking ID #2.
Your previous booking date was: 2022-12-25

Initating booking update...

Do you want to complete the booking? (y/n)  y

Your new booking date is 2022-12-15

In [47]:
#Create add booking procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()
    
    #Drops existing procedure under the same name
    drop_procedure = """
        DROP PROCEDURE IF EXISTS `AddBooking`;
    """
    cursor.execute(drop_procedure)
    
    #Execute query
    create_addbooking = """            
            CREATE PROCEDURE `AddBooking`(IN date DATE, IN table_no INT)
            BEGIN
                DECLARE check_res BOOLEAN;
                
                START TRANSACTION;
                    
                SELECT COUNT(*) INTO check_res FROM Bookings WHERE BookingDate = date AND TableNumber = table_no;

                IF check_res THEN
                    ROLLBACK;
                    SELECT "The date and table is already booked.";
                        
                ELSE
                    INSERT INTO Bookings (BookingDate, TableNumber) VALUES (date, table_no); 
                    COMMIT;

                END IF;
            END
    """
    cursor.execute(create_addbooking)

    print("MySQL procedure successfully created")

    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

MySQL procedure successfully created

In [23]:
#Using add booking procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()

    #Asking for user-input
    table_no = input("Please enter your desired table number: ")
    booking_date = input("Please enter your desired Booking Date (YYYY-MM-DD): ")

    #Convert Booking ID to integer if necessary
    table_no = int(table_no)
    
    #SQL query to check previous booking date & execute
    booking = """
    SELECT BookingID, BookingDate, TableNumber FROM Bookings WHERE BookingDate = %s;
    """
    cursor.execute(booking, (booking_date,))
    booking_results1 = cursor.fetchall()
    
    print("\nChecking Booking...\n")
    
    print(f"On {booking_date}, the tables booked are: ")
    for i in booking_results1:
        print(f"Table number: {i[2]}")

    #Calling procedure to update
    add_booking = """            
            CALL AddBooking(%s, %s)
    """
    cursor.execute(add_booking, (booking_date, table_no))
    check_booking = cursor.fetchall()
    for i in check_booking:
        print(i[0])

    if i[0] == 'The date and table is already booked.':
        print("The add booking process has been cancelled.")
    
    else:
        confirm = input("\nLooks like the table is available on that date! Do you want to complete the booking? (y/n)")
        if confirm == 'y':
            connection.commit()
            
            cursor.execute(booking, (booking_date,))
            booking_results2 = cursor.fetchall()
            for i in booking_results2:
                new_table = i[-1]
            print(f"\nAwesome, your new booking information is:\nDate: {booking_date}\nTable Number: {new_table}")
                
        else:
            print("The add booking process is cancelled.")    
    
    cursor.close()
    
except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

Please enter your desired table number:  11
Please enter your desired Booking Date (YYYY-MM-DD):  2022-12-25

Checking Booking...

On 2022-12-25, the tables booked are:

Looks like the table is available on that date! Do you want to complete the booking? (y/n) y

Awesome, your new booking information is:
Date: 2022-12-25
Table Number: 11

In [5]:
#Create cancel booking procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()

    #Drops existing procedure under the same name
    drop_procedure = """
        DROP PROCEDURE IF EXISTS `CancelBooking`;
    """
    cursor.execute(drop_procedure)
    
    #Execute query
    create_cancelbooking = """            
            CREATE PROCEDURE `CancelBooking`(IN booking_id INT)
            BEGIN
               DELETE FROM Bookings
               WHERE BookingID = booking_id;
            END
    """
    cursor.execute(create_cancelbooking)

    print("MySQL procedure successfully created")

    cursor.close()

except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

MySQL procedure successfully created

In [35]:
#Using cancel booking procedure

try:
    #Establish connection to server
    connection = connector.connect(
        user = user, 
        password = password,
        db = db)

    #Create cursor object
    cursor = connection.cursor()

    #Asking for user-input
    booking_id = input("Please enter your booking ID: ")
    

    #Convert Booking ID to integer if necessary
    booking_id = int(booking_id)
    
    #SQL query to check show bookings date & execute
    booking = """
    SELECT BookingID, BookingDate, TableNumber FROM Bookings WHERE BookingID = %s;
    """
    cursor.execute(booking, (booking_id,))
    booking_results1 = cursor.fetchall()

    #Looping through booking results for cleaner print statement
    for t in booking_results1:
        pass
        
    print("\nChecking Booking...\n")
    
    print(f"Booking ID # {booking_id} has booked table # {t[2]} on {t[1]}")

    confirmation = input("\nWould you like to cancel the booking? (y/n): ")

    if confirmation == 'y':
        cancel_booking = """
        CALL CancelBooking(%s)
        """
        cursor.execute(cancel_booking, (booking_id,))
        connection.commit()
        print(f"\nBooking ID # {booking_id} has been cancelled")

    else:
        print(f"\nBooking ID # {booking_id} remains booked for table # {t[2]} on {t[1]}")
    
    cursor.close()
    
except connector.Error as err:
    print(f"Error: {err}")

finally:
    if connection.is_connected():
        connection.close()

Please enter your booking ID:  11

Checking Booking...

Booking ID # 11 has booked table # 12 on 2022-12-15

Would you like to cancel the booking? (y/n):  y

Booking ID # 11 has been cancelled